#!/usr/bin/env ruby

# public resolvers
# last update: 20180402
resolvers = {
	CloudFlare1: '1.1.1.1',
	CloudFlare2: '1.0.0.1',
	Comodo1: '8.26.56.26',
	Comodo2: '8.20.247.20',
    CCDNS1: '156.154.70.22',
    CSDNS2: '156.154.71.22',
    CSDNS3: '8.26.56.26',
    ClaraNet1: '212.82.225.7',
    ClaraNet2: '212.82.226.212',
    DA1: '156.154.70.1',
    DA2: '156.154.71.1',
    Dyn: '216.146.35.35',
    Google1: '8.8.8.8',
    Google2: '8.8.4.4',
    HE: '74.82.42.42',
    Level31: '209.244.0.4',
    Level32: '209.244.0.3',
    NCS: '198.153.192.40',
    OpenDNS1: '208.67.220.220',
    OpenDNS2: '208.67.222.222',
    SafeDNS: '195.46.39.39',
    censurfridns: '89.233.43.71',
    puntCAT: '109.69.8.51',
}

threads = []
@results = []
resolvers.each { |k, v|
    threads << Thread.new {
        m = "Digging @ #{k}"
        r = %x( dig @#{v.to_s} #{ARGV.join( ' ' )} )

        @results << [ m, r ]
    }
}

threads.each { |thr| thr.join }

@results.each { |p,i|
    puts <<"EOF"
---
Provider: #{p}
#{i}
EOF

}

